version: "3.9"

networks:
  jenkins-net:
    external: true

services:
  jenkins-server:
    image: "jenkins/jenkins:lts"
    restart: unless-stopped
    ports:
      - "5555:8080"
    networks:
      - "jenkins-net"
    volumes:
      - jenkins-data:/var

volumes:
  jenkins-data:
